
'use strict';document.addEventListener('DOMContentLoaded',function(){var header=document.querySelector('.header');var menuArrows=document.querySelectorAll('.menu__arrow');var menu=document.querySelector('.menu');var burger=document.querySelector('.header__burger');var menuSubLinks=document.querySelectorAll('.menu__sub-link');var titles=document.querySelectorAll('.title');var subtitles=document.querySelectorAll('.subtitle');menuArrows.forEach(function(arrow){arrow.addEventListener('click',function(){arrow.classList.toggle('menu__arrow--active');arrow.nextElementSibling.classList.toggle('menu__sub-list--open');});});var lastScroll=0;var scrollPosition=function scrollPosition(){return window.pageYOffset||document.documentElement.scrollTop;};window.addEventListener('scroll',function(){if(lastScroll>50){header.classList.add('paint');}else{header.classList.remove('paint');}
lastScroll=scrollPosition();if(window.pageYOffset>200||document.documentElement.scrollTop>200){document.querySelector('.scroll-top').classList.add('scroll-top--show');}else{document.querySelector('.scroll-top').classList.remove('scroll-top--show');}});if(window.pageYOffset>200||document.documentElement.scrollTop>200){document.querySelector('.scroll-top').classList.add('scroll-top--show');header.classList.add('paint');}else{document.querySelector('.scroll-top').classList.remove('scroll-top--show');header.classList.remove('paint');}
burger.addEventListener('click',function(){burger.classList.toggle('burger--active');header.classList.toggle('header--open-menu');menu.classList.toggle('menu--active');document.body.classList.toggle('lock');});menuSubLinks.forEach(function(link){link.addEventListener('click',function(){burger.classList.remove('burger--active');header.classList.remove('header--open-menu');menu.classList.remove('menu--active');document.body.classList.remove('lock');});});titles.forEach(function(title){return title.dataset.duplicate=title.textContent;});subtitles.forEach(function(subtitle){return subtitle.dataset.duplicate=subtitle.textContent;});if(document.getElementById('callback-form')){$('#callback-form').on('submit',function(e){e.preventDefault();var m_method=$(this).attr('method');var m_action=$(this).attr('action');var m_data=$(this).serialize();$('#form').addClass('sending');$.ajax({type:m_method,url:m_action,data:m_data,resetForm:'true',success:function success(result){$('#form').removeClass('sending');$('#popup-thx').addClass('open');setTimeout(function(){$('#popup-thx').removeClass('open');$('#form')[0].reset();},3000);}});});}
document.querySelectorAll('.tabs__trigger').forEach(function(trigger){trigger.addEventListener('click',function(e){e.preventDefault();var id=e.target.getAttribute('href').replace('#','');document.querySelectorAll('.tabs__trigger').forEach(function(child){return child.classList.remove('tabs__trigger--active');});document.querySelectorAll('.tabs__item').forEach(function(child){return child.classList.remove('tab--active');});trigger.classList.add('tabs__trigger--active');document.getElementById(id).classList.add('tab--active');});});if(document.querySelector('.tabs__trigger')){document.querySelector('.tabs__trigger').click();}
if(document.querySelector('.tab__slider')){new Swiper('.tab__slider',{navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev'},scrollbar:{el:'.swiper-scrollbar',draggable:true},observer:true,observeParents:true,observeSlideChildren:true,spaceBetween:24,keyboard:{enabled:true,onlyInViewport:true,pageUpDown:true},slideToClickedSlide:false,breakpoints:{320:{slidesPerView:1},426:{slidesPerView:1.5},768:{slidesPerView:2.5},1025:{slidesPerView:3}}});}});'use strict';var popupLinks=document.querySelectorAll('.popup-link');var body=document.querySelector('body');var lockPadding=document.querySelectorAll('.lock-padding');var unlock=true;var timeout=400;document.addEventListener('click',function(e){if(e.target.closest('.popup-link.playlist__link')){var url=e.target.closest('.popup-link.playlist__link').dataset.url;var popupName=e.target.closest('.popup-link.playlist__link').getAttribute('href').replace('#','');var currentPopup=document.getElementById(popupName);popupOpen(currentPopup);e.preventDefault();currentPopup.querySelector('iframe').setAttribute('src',url);currentPopup.querySelector('.popup__title').textContent=e.target.closest('.popup-link.playlist__link').querySelector('.link__title').textContent;}
if(e.target.closest('.tab__link.popup-link')){var _popupName=e.target.closest('.tab__link.popup-link').getAttribute('href').replace('#','');var _currentPopup=document.getElementById(_popupName);popupOpen(_currentPopup);e.preventDefault();}
if(e.target.closest('#to-request')){setTimeout(function(){popupClose(e.target.closest('#to-request').closest('.popup'));});}});var popupCloseIcon=document.querySelectorAll('.close-popup');if(popupCloseIcon.length>0){var _loop=function _loop(index){var el=popupCloseIcon[index];el.addEventListener('click',function(e){popupClose(el.closest('.popup'));e.preventDefault();});};for(var index=0;index<popupCloseIcon.length;index++){_loop(index);}}
function popupOpen(currentPopup){if(currentPopup&&unlock){var popupActive=document.querySelector('.popup.open');if(popupActive){popupClose(popupActive,false);}else{bodyLock();}
currentPopup.classList.add('open');currentPopup.addEventListener('click',function(e){if(!e.target.closest('.popup__content')){popupClose(e.target.closest('.popup'));}});}}
function popupClose(popupActive){var doUnlock=arguments.length>1&&arguments[1]!==undefined?arguments[1]:true;if(unlock){popupActive.classList.remove('open');if(doUnlock){bodyUnlock();}}}
function bodyLock(){var lockPaddingValue=window.innerWidth-document.querySelector('.wrapper').offsetWidth+'px';if(lockPadding.length>0){for(var index=0;index<lockPadding.length;index++){var _el=lockPadding[index];_el.style.paddingRight=lockPaddingValue;}}
body.style.paddingRight=lockPaddingValue;body.classList.add('lock');unlock=false;setTimeout(function(){unlock=true;},timeout);}
function bodyUnlock(){setTimeout(function(){if(lockPadding.length>0){for(var index=0;index<lockPadding.length;index++){var _el2=lockPadding[index];_el2.style.paddingRight='0px';}}
body.style.paddingRight='0px';body.classList.remove('lock');},timeout);unlock=false;setTimeout(function(){unlock=true;},timeout);}
document.addEventListener('keydown',function(e){if(e.which===27){var popupActive=document.querySelector('.popup.open');popupClose(popupActive);}});(function(){if(!Element.prototype.closest){Element.prototype.closest=function(css){var node=this;while(node){if(node.matches(css))return node;else node=node.parentElement;}
return null;};}})();(function(){if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector;}})();